--- 
title: "Formation au Tidyverse pour l'agroécologie"
author: "Oswaldo Forey"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "Plan de la formation au Tidyverse."
---

# Objectifs de la formation

<div align="justify">

L’objectif pédagogique de cette formation est d’acquérir les bases
nécessaires du langage Tidyverse du logiciel R pour manipuler ses
tableaux de données (transformation de variables, fusion de tableaux,
calculs, etc.) et produire ses graphiques (c’est à dire les étapes de
l’analyse de données en amont de l’analyse statistique), le tout
intégralement avec le paquet (package) Tidyverse du logiciel R.
L’objectif est ainsi de permettre une transition d’Excel à R et au
Tidyverse, R étant plus adapté et plus puissant pour effectuer ces
tâches, et le langage du Tidyverse plus facile à apprendre que le
langage de base de R. <strong>Cette formation s’adresse à des débutant-e-s</strong> est à l’avantage et
l’originalité d’être <strong>entièrement basée sur le nouveau langage du
paquet Tidyverse, plus simple à apprendre et manipuler que le langage de
base de R</strong>, dont la complexité est le frein majeur à son
utilisation par les néophytes.

</div>

<br>

----

A l’issu de la formation, les participant-e-s seront capable de :

- Installer R et RStudio, installer un package, utiliser RStudio

- Charger un tableau de données, vérifier et déclarer les types des
    variables (dataframe, vecteur, facteur, date)

- Effectuer les manipulation de données les plus courantes: filtrer
    des lignes, sélectionner des colonnes, faire des opérations
    (moyennes, écart-types) groupées selon certaines conditions
    (modalités, traitements, année, etc.), rajouter des colonnes, faire
    un calcul entre colonnes, compter des observations, fusionner des
    tableaux de tailles différentes, restructurer un tableau au bon
    format, corriger des chaines de caractères, séparer les données
    d’une colonne en plusieurs colonnes

- Faire différents types de graphiques (points, lignes, boxplots,
    histogrammes) et améliorer l’esthétique pour la publication
    (couleurs, limites des axes, police, légendes)

- Générer un rapport html, word ou pdf à partir du code et améliorer
    son esthétique avec Rmarkdown

----


